from dotenv import load_dotenv
import os

load_dotenv()
TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY")
GROQ_API_KEY=os.getenv("GROQ_API_KEY")
BASE_URL_TOGETHER_AI=os.getenv("BASE_URL")
BASE_URL_GROQ=os.getenv("BASE_URL_GROQ")
VISION_MODEL=os.getenv("VISION_MODEL")
REASONING_MODEL=os.getenv("REASONING_MODEL")
MULTI_MODEL=os.getenv("MULTI_MODEL")
DISTILL_LLAMA_TOGETHER_AI_70B=os.getenv("DISTILL_LLAMA_TOGETHER_AI_70B")
DISTILL_LLAMA_GROQ=os.getenv("DISTILL_LLAMA_GROK-70B")
GROQ_LLAMA_3_8B=os.getenv("GROQ_LLAMA_3_8B")
